[options]
addons_path = /Users/aos/projects/odoo/odoo18.0/odoo, /Users/aos/projects/odoo/odoo18.0/addons, /Users/aos/projects/odoo/odoo18addons/design-themes, /Users/aos/projects/odoo/odoo18addons/addons-2nd, /Users/aos/projects/odoo/odoo18addons/addons-3rd, /Users/aos/projects/odoo/odoo18addons/addons-3rd/mobilesite,/Users/aos/projects/odoo/odoo18addons/addons-3rd/ai,/Users/aos/projects/odoo/odoo18addons/addons-3rd/membership,
# , /Users/aos/projects/odoo/odoo18.0/addons_2rd/om_account_accountant
# addons_path = /Users/aos/projects/odoo/odoo18.0/odoo, /Users/aos/projects/odoo/odoo18.0/addons, /Users/aos/projects/odoo/odoo18.0/odoo/addons, /Users/aos/projects/odoo/design-themes
admin_passwd = $pbkdf2-sha512$600000$0tr731vL.R.jFEKIUcrZGw$UeahvcdDHFcdiM8jJe8XU8gX.xMrrFupWmBUk31rSZJduopRN0chbEb2rtRcYdwAD1ZIa6vpPF7pahay1ki1jQ
csv_internal_sep = ,
data_dir = /Users/aos/Library/Application Support/Odoo18.0
db_host = localhost
db_maxconn = 128
db_maxconn_gevent = False
db_name = False
db_password = ji3g-t9wx-68qy
db_port = 5418
db_sslmode = prefer
db_template = template0
db_user = odoo
dbfilter =
demo = {}
geoip_city_db = /usr/share/GeoIP/GeoLite2-City.mmdb
geoip_country_db = /usr/share/GeoIP/GeoLite2-Country.mmdb
email_from = False
from_filter = False
gevent_port = 8072
http_enable = True
http_interface = 0.0.0.0
http_port = 8069
import_partial =
longpolling_port = 8072
limit_memory_hard = 8192000000
limit_memory_soft = 4096000000
limit_request = 65536
limit_time_cpu = 180
limit_time_real = 360
limit_time_real_cron = -1
list_db = True
log_db = False
log_db_level = warning
log_handler = :INFO
log_level = info
logfile =
max_cron_threads = 1
osv_memory_count_limit = 0
pg_path =
pidfile =
proxy_mode = False
reportgz = False
screencasts =
# ; screenshots = /private/var/folders/77/qjb4y0d939v9fg45_8frknnh0000gn/T/odoo_tests
server_wide_modules = base,web
smtp_password = False
smtp_port = 25
smtp_server = localhost
smtp_ssl = False
smtp_ssl_certificate_filename = False
smtp_ssl_private_key_filename = False
smtp_user = False
syslog = False
test_enable = False
test_file =
test_tags = None
transient_age_limit = 1.0
translate_modules = ['all']
unaccent = False
upgrade_path =
without_demo = False
workers = 4
websocket = False